spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    gateway:
      mvc:
        routes:
          - id: test_route
            uri: https://www.baidu.com
            predicates:
              - Query=url, baidu # url参数中包含baidu
          - id: qq_route
            uri: https://www.qq.com
            predicates:
              - Query=url, qq # url参数中包含qq
  application:
    name: gulimall-gateway
server:
  port: 88